version: '3'
services:
  dotnetcore-base:
    build:
      context: .
      dockerfile: ./test/test.Dockerfile
    command: dotnet test test/dotnetcore-base.Test/dotnetcore-base.Test.csproj
    depends_on:
      - rabbitmq
      - rabbitmq-mgmt
      - mysql
    environment:
      LOG_LEVEL: debug
      NODE_ENV: dev
      RABBIT_MANAGEMENT: rabbitmq-mgmt
    links:
      - rabbitmq-mgmt:rabbitmq-mgmt
    ports:
      - 6502:6502
    volumes:
      - ./:/home/app/src

  rabbitmq:
    image: rabbitmq:3.6
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672

  rabbitmq-mgmt:
    image: rabbitmq:3-management
    depends_on:
      - rabbitmq
    ports:
      - 15672:15672

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: pacifica
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_USER: admin
      MYSQL_PASSWORD: dogfood
    ports:
      - "3306:3306"