version: '3'
services:
  dotnetcore-base:
    build:
      context: .
      dockerfile: ./test/test.Dockerfile
    command: dotnet test test/dotnetcore-base.Test/dotnetcore-base.Test.csproj
    depends_on:
      - rabbitmq
      - rabbitmq-mgmt
      - mssql
      - redis
    environment:
      LOG_LEVEL: debug
      NODE_ENV: dev
      RABBIT_MANAGEMENT: rabbitmq-mgmt
      SQL_USERNAME: sa
      SQL_PASSWORD: s3cr3!t123
      SQL_HOST: mssql
      SQL_PORT: 1433
      ELASTICACHE_HOST: redis
      ELASTICACHE_PORT: 6379
    ports:
      - 5001:5001
      - 5000:5000
    volumes:
      - ./:/home/app/src

  rabbitmq:
    image: rabbitmq:3.6
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672

  rabbitmq-mgmt:
    image: rabbitmq:3.6-management
    depends_on:
      - rabbitmq
    ports:
      - 15672:15672

  mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: s3cr3!t123
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  redis:
    image: redis:2.8.6
    ports:
      - 6379:6379